name: Test and Build Expo App

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Create .env
        run: |
          cat > .env << EOF
          EXPO_PUBLIC_BASE_URL=${{ secrets.EXPO_PUBLIC_BASE_URL }}
          EXPO_PUBLIC_CLOUDINARY_URL=${{ secrets.EXPO_PUBLIC_CLOUDINARY_URL }}
          EXPO_PUBLIC_CLOUDINARY_PRESET_NAME=${{ secrets.EXPO_PUBLIC_CLOUDINARY_PRESET_NAME }}
          EOF

      - name: Run Jest Tests
        run: npm test -- --ci

      - name: Setup Expo CLI
        run: npm install -g eas-cli

      - name: Login to Expo
        run: eas whoami || eas login --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Trigger Android Build
        run: eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
